services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: machine_monitoring
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    networks:
      - my_network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    container_name: pgadmin
    depends_on:
      - postgres
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
